export default {
  container: {
    padding: 22,
    backgroundColor: "#edf0e9",
  },
  textInput: {
    borderColor: "gray",
    width: "100%",
    borderWidth: 1,
    borderRadius: 10,
    padding: 7,
  },
  text: {
    margin: 5,
    fontWeight: "bold",
  },
  fatButton: {
    margin: 10,
  },
  calculateButton: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#ff5c5c",
    borderRadius: 10,
    padding: 10,
    margin: 10,
  },

  result: {
    alignSelf: "center",
    color: "gray",
    fontSize: 45,
    padding: 15,
  },
  buttonContainer: {
    minWidth: 320,
    minHeight: 500,
    backgroundColor: "white",
    borderRadius: 10,
    padding: 12,
    shadowColor: "black",
    shadowOpacity: 0.5,
    shadowRadius: 3,
    shadowOffset: {
      height: 0,
      width: 0,
    },
    elevation: 2,
  },
  buttonContainer2: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    height: 120,
    width: 160,
    backgroundColor: "white",
    borderRadius: 10,
    padding: 2,
    margin: 10,
    shadowColor: "black",
    shadowOpacity: 0.5,
    shadowRadius: 3,
    shadowOffset: {
      height: 0,
      width: 0,
    },
    elevation: 2,
  },
};
