export default {
  container: {
    padding: 22,
    alignItems: "center",
  },
  textInput: {
    borderColor: "gray",
    width: "100%",
    borderWidth: 1,
    borderRadius: 10,
    padding: 7,
  },
  text: {
    margin: 5,
    fontWeight: "bold",
  },
  fatButton: {
    margin: 10,
  },
  calculateButton: {
    backgroundColor: "#ff5c5c",
    borderRadius: 10,
    padding: 10,
    alignItems: "center",
    justifyContent: "center",
    margin: 10,
    marginLeft: 40,
    marginRight: 40,
  },
  result: {
    alignSelf: "center",
    color: "gray",
    fontSize: 65,
    padding: 15,
  },
  buttonContainer: {
    width: 300,
    height: 240,
    backgroundColor: "white",
    borderRadius: 10,
    padding: 12,
    shadowColor: "black",
    shadowOpacity: 0.5,
    shadowRadius: 3,
    shadowOffset: {
      height: 0,
      width: 0,
    },
    elevation: 2,
  },
  buttonContainer2: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    minWidth: 300,
    minHeight: 120,
    backgroundColor: "white",
    borderRadius: 10,
    padding: 5,
    marginTop: 5,
    shadowColor: "black",
    shadowOpacity: 0.5,
    shadowRadius: 3,
    shadowOffset: {
      height: 0,
      width: 0,
    },
    elevation: 2,
  },
};
