export default {
  container: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    height: "100%",
  },
  headerText: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    fontSize: 25,
    fontWeight: "bold",
    alignSelf: "center",
    textTransform: "uppercase",
    margin: 20,
  },

  appButtonContainer: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    elevation: 8,
    backgroundColor: "yellow",
    borderRadius: 10,
    padding: 30,
    margin: 15,
  },
  mainText: {
    fontSize: 18,
    color: "#fff",
    fontWeight: "bold",
    alignSelf: "center",
    textTransform: "uppercase",
  },

  calText: {
    fontWeight: "bold",
  },
  buttonContainer: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: 260,
    height: 390,
    backgroundColor: "white",
    borderRadius: 10,
    padding: 12,
    shadowColor: "black",
    shadowOpacity: 0.5,
    shadowRadius: 3,
    shadowOffset: {
      height: 0,
      width: 0,
    },
    elevation: 2,
  },
  buttonContainer2: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: 250,
    height: 85,
    backgroundColor: "white",
    borderRadius: 10,
    padding: 12,
    marginTop: 20,
    shadowColor: "black",
    shadowOpacity: 0.5,
    shadowRadius: 3,
    shadowOffset: {
      height: 1,
      width: 0,
    },
    elevation: 2,
  },
};
